### PR TITLE
fix(nestjs-typegoose): make TypegooseClass an alias of AnyParamConstructor

### PR DESCRIPTION
**Pull request by jacobk999**
Makes `TypegooseClass` an alias of `AnyParamConstructor<unknown` to keep feature parity with `@typegoose/typegoose`

### CODE REVIEW

**Comment by smolinari** [comment]
Hey Jacob,

Thanks for putting this together. Question, are you expecting to use a class with a constructor function as a Typegoose class/ your Mongoose schema / entity?

I ask because, Typegoose classes shouldn't ever be constructors. 

Scott

**Comment by jacobk999** [comment]
Yes.
My use case is basically taking data from an external rest api and processing it into a class and then storing that processed class in mongo.

Here is an example: https://github.com/Statsify/statsify/blob/main/packages/schemas/src/player/index.ts

The @Field decorator is a wrapper around the @prop decorator and a few other things.

Then to create an instance I just make a request to the external api and do new Player(data). I could just use a static method to process it the data into an object but it seems silly to not just use the builtin constructor. 

I actually have been using an old version of this package so I only noticed that this functionality wasn't available today.

**Comment by smolinari** [comment]
I'm sort of confused. Are you trying to rewrite your app into a Nest app? Cause, your app isn't a NestJS app, is it?

Scott

**Comment by jacobk999** [comment]
Sorry, I should have explained more. It is a monorepo setup with a nest app in the apps/api folder

For example here is the player module: https://github.com/Statsify/statsify/blob/main/apps/api/src/player/player.module.ts

The models are separated from the nest api because they need to be accessed by other projects.

**Comment by smolinari** [comment]
So, I'm still a bit confused. When did this error start happening? Or, why is the current code a problem now? What changed?

This is a niche problem to say the least, because again, Typegoose classes shouldn't be constructors. 

Lastly, from a programming design perspective, your schema classes are doing more than one thing (has more than one reason to be fixed or enhanced), which breaks SRP (i.e. the S in SOLID). 

> My use case is basically taking data from an external rest API and processing it into a class and then storing that processed class in mongo.

So, I'm reluctant to make the change currently. I'm also not certain it won't cause knock-on issues with others, despite it being a simple change. I can't currently count this out. 

Scott

**Comment by jacobk999** [comment]
This error started happening when I updated the package from `8.1.0` to `11.0.1`.
It shouldn't cause any issues with others because it is just widening the scope of types of classes the type accepts. 
The no-constructor functionality still works. The type also used to have this functionality: https://github.com/m8a-io/m8a/blob/6f6637fd9795aab19923d22b476d9e1c865f106a/deps/nestjs-typegoose/src/typegoose-class.interface.ts#L3-L5

In terms of breaking SRP, I believe it is better to have the class process the data and handle the responsibility of being the mongoose model because if they were separated it would cause more issues keeping them in sync and would hurt the developer experience. It would cause lots of repeated code for no reason. 

It is much easier to use this than the second example and the whole point of typegoose is to reduce redundancy. 
```ts
class Car {
	@prop()
	model: string;

	constructor(model: string) {
		this.model = model;
	}
}
```

```ts
interface Car {
	model: string;
}

function makeCar(model: string): Car {
	return {
		model,
	}
}

const CarModel = mongoose.model("Car", {
	model: String
});
```

**Comment by smolinari** [comment]
I now know why this got changed. It is because I have the ESLint (tslint-plugin) rule `no-explicit-any`.  I tried to change the code back and got the error and remembered. 

> if they were separated it would cause more issues keeping them in sync

Your class doing more than one thing has caused you to write this PR. That is also extra effort. :P 

Sure, it's a simple change, but it is a change for something that Typegoose entity classes shouldn't be doing in the end.

Don't forget the cognitive load such a mix of responsibilities will have on a new dev. The usage of the entity to also do external API calls is very far from Nest-like and doesn't follow Clean Code/ Onion Architecture, so it will probably confuse any new regular devs at first. The effort to learn or explain how you've mixed responsibilities is also time and effort that will be needed. Of course, if it is just your own work with only you continuing to work on it, no loss. But then, still not a real reason to change for e. The more I think about it, the more I'm reluctant to go forward with this PR. 

You still have some choices. 

1. Create your own version of the module. It's not a ton of code. I'm offering this "do a copy-and-paste", cause I doubt you'll want this whole monorepo in a fork just for the module code. And yes you'll need to keep up with changes and not forking may mean more maintenance work. But, the package won't be changing much, if at all. I've also decided to turn on `noImplicitAny` in `tsconfig` and I'll be putting out another version here soon.   

2. Fix your code to have entities that only deal with being metadata for Typegoose.  

Sorry if that seems heartless. I'm not trying to be that on purpose. I'm just not seeing the practical reasons to bend the module's code to fit the (niche) needs of your app, especially when it works as-is for everyone else.   

I'll listen to any other reasoning you may have, if you wish to continue the discussion. 

Scott

**Comment by jacobk999** [comment]
Now that I am looking at it, maybe this type should not exist at all. 
The official Typegoose library already has a type for constructors that allows this use case. 
https://github.com/typegoose/typegoose/blob/1efd6881e5560eec62ac5d0f75b1957e7805a604/src/types.ts#L40
and it is exported
https://github.com/typegoose/typegoose/blob/1efd6881e5560eec62ac5d0f75b1957e7805a604/src/typegoose.ts#L64
I don't think this library should put any extra restrictions on what is already possible with Typegoose.

**Comment by smolinari** [comment]
If you want to, do make that change, I'd appreciate it. I'd agree we don't want to limit what Typegoose also allows. 

Scott

**Comment by jacobk999** [comment]
Welp, it seems like rush did it for me.

**Comment by smolinari** [comment]
Thanks for this. Release coming soon!

Scott

**Comment by smolinari** [comment]
11.0.2 has been released. Thanks again!

Scott

**Pull request merged**
